import fs from "fs";
import path from "path";
import type { Transaction, PricePoint } from "./types";

const DATA_DIR = path.join(process.cwd(), "data");

/**
 * Load the synthetic transaction ledger from data/synthetic_ledger.csv.
 * The CSV is generated by scripts/generate_data.py and is intentionally
 * simple (no quoted fields), so a plain split-on-comma parse is safe.
 */
export function loadTransactions(): Transaction[] {
  const raw = fs.readFileSync(
    path.join(DATA_DIR, "synthetic_ledger.csv"),
    "utf-8",
  );
  const lines = raw.trim().split("\n");
  return lines.slice(1).map((line) => {
    const cols = line.split(",");
    return {
      date: cols[0],
      source: cols[1],
      action: cols[2],
      btc: Number(cols[3]),
      usd: Number(cols[4]),
      fees: Number(cols[5]),
    };
  });
}

/** Load the weekly BTC price history from data/btc_price_history.json. */
export function loadPriceHistory(): PricePoint[] {
  const raw = fs.readFileSync(
    path.join(DATA_DIR, "btc_price_history.json"),
    "utf-8",
  );
  return JSON.parse(raw) as PricePoint[];
}
