import { loadTransactions, loadPriceHistory } from "@/lib/data";
import { computeSnapshot, computeHoldingsSeries } from "@/lib/portfolio";
import { TopBar } from "@/components/TopBar";
import { SnapshotGrid } from "@/components/SnapshotGrid";
import { HoldingsChart } from "@/components/HoldingsChart";

export default function Page() {
  const transactions = loadTransactions();
  const priceHistory = loadPriceHistory();
  const latest = priceHistory[priceHistory.length - 1];
  const snapshot = computeSnapshot(transactions, latest.price, latest.date);
  const series = computeHoldingsSeries(transactions, priceHistory);

  return (
    <main className="mx-auto max-w-5xl px-5 py-8">
      <TopBar snapshot={snapshot} />
      <SnapshotGrid snapshot={snapshot} />
      <div className="mt-3">
        <HoldingsChart data={series} />
      </div>
      <footer className="mt-6 text-[11px] leading-relaxed text-faint">
        {snapshot.txCount.toLocaleString()} synthetic transactions across Strike,
        Coinbase, Cash App and Swan. All figures are demo data generated by{" "}
        <code className="text-muted">scripts/generate_data.py</code> — not real
        holdings.
      </footer>
    </main>
  );
}
